version: "3"

networks:
  grafana:

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:1.4.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:v1.3.0
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - grafana

  grafana:
    image: grafana/grafana:7.0.4
    ports:
      - 3000:3000
    networks:
      - grafana

  app:
    build: ./app
    ports:
      - 8081:80
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana
