apiVersion: 1
groups:
    - orgId: 1
      name: fundamentals
      folder: fundamentals
      interval: 10s
      rules:
        - uid: c2c9d9dc-60f6-4eab-9742-4641f3e3da8d
          title: 'fundamentals-test '
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: sum(rate(tns_request_duration_seconds_count[5m])) by(route)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.2
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: b98ede9d-e7e6-4706-b4d2-dd26fa22e66e
          panelId: 2
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: b98ede9d-e7e6-4706-b4d2-dd26fa22e66e
            __panelId__: "2"
            summary: High Traffic!
          labels: {}
          isPaused: false
